export enum UserEventType {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  PRODUCT_CREATE = 'PRODUCT_CREATE',
  PRODUCT_UPDATE = 'PRODUCT_UPDATE',
  PRODUCT_DELETE = 'PRODUCT_DELETE',
  CATEGORY_CHANGE = 'CATEGORY_CHANGE',
  PERMISSION_CHANGE = 'PERMISSION_CHANGE',
  SETTINGS_UPDATE = 'SETTINGS_UPDATE',
  EXPORT_DATA = 'EXPORT_DATA',
  IMPORT_DATA = 'IMPORT_DATA'
} 